#!/bin/bash

################################################################
                  ##                     __   ____  _  _    
                 ####                   / _\ (  _ \( \/ )    
                ######                 /    \ )   // \/ \ 
               ########                \_/\_/(__\_)\_)(_/   
              ##########          ___  __   __ _  ____  __  ___ 
             ############        / __)/  \ (  ( \(  __)(  )/ __)
            ##############      ( (__(  O )/    / ) _)  )(( (_ \
           ################      \___)\__/ \_)__)(__)  (__)\___/
          ######      ######           _  _  ____  __  __   
         #######      #######         / )( \(_  _)(  )(  )  
       #######         #######        ) \/ (  )(   )( / (_/\ 
      ######             ######       \____/ (__) (__)\____/ 
     ###                     ###    
################################################################
# arch(arm)-config-util (acu) is a configuration utility for Arch Linux ARM (Aarch64) 
# currently with main focus on the Radxa Rock 5 and RK3588
# acu provides some similar features with armbian-config or raspi-config or rsetup but for Arch Linux
# acu provides a pacman (and other package manager) wrapper with additional features (such as installing packages from a github release based repo, from URL, compiling and installing packages from source (PKGBUILD), etc.)
################################################################
# acu release configurations (FOR DEVELOPERS ONLY, DO NOT MODIFY)

# utilname
# name of this utility (used for title)
utilname="Arch (ARM) Configuration Utility"

# ACU Release Version : (github tags) (or branch*)
release="0.0.4-dev"

# ACU Build Number: utilver (YYMMDDNN)
utilver=24031299

# Remote Repository for update check
remote_repo="https://github.com/kwankiu/acu"

# update_available
# acu uses this variable to determine whether to show the "update available" menu option
# note: you should never set this to true
update_available=false

# for detecting system architecture
system_arch=$(uname -m)

# Note: for acu user configurations, please edit $HOME/.acu/config/config.yaml or --loadconfig
config_file="$HOME/.acu/config/config.yaml"

################################################################
# Tools for formatting / styling

# Define terminal color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;36m'
DEBUG='\033[0;37m'
NC='\033[0m' # No Color

# sudo override
sudo () {
    local command=$@
    if [ "$(id -u)" -eq 0 ]; then
        #echo "Running in root."
        command "$@"
    else
        #echo "Running with sudo."
        command sudo "$@"
    fi
}

# clear override
clear () {
    local command=$@
    if [ -z "$no_clear" ]; then
        command clear "$@"
    fi
}

# acu override (just for development use)
#   acu () {
#       local command=$@
#       command bash $HOME/Documents/GitHub/acu/acu "$@"
#   }

# Option Picker
function select_option {

    # Little helpers for terminal print control and key input
    ESC=$( printf "\033")
    cursor_blink_on()  { printf "$ESC[?25h"; }
    cursor_blink_off() { printf "$ESC[?25l"; }
    cursor_to()        { printf "$ESC[$1;${2:-1}H"; }
    print_option()     { printf "   $1 "; }
    print_selected()   { printf "  $ESC[7m $1 $ESC[27m"; }
    get_cursor_row()   { IFS=';' read -sdR -p $'\E[6n' ROW COL; echo ${ROW#*[}; }
    key_input()        { read -s -n3 key 2>/dev/null >&2
                         if [[ $key = $ESC[A ]]; then echo up;    fi
                         if [[ $key = $ESC[B ]]; then echo down;  fi
                         if [[ $key = ""     ]]; then echo enter; fi; }

    # Initially print empty new lines (scroll down if at bottom of screen)
    for opt; do printf "\n"; done

    # Determine current screen position for overwriting the options
    local lastrow=`get_cursor_row`
    local startrow=$(($lastrow - $#))

    # Ensure cursor and input echoing back on upon a ctrl+c during read -s
    trap "cursor_blink_on; stty echo; printf '\n'; exit" 2
    cursor_blink_off

    local selected=0
    while true; do
        # Print options by overwriting the last lines
        local idx=0
        local max_width=$(tput cols)
        for opt; do
            cursor_to $(($startrow + $idx))
            local formatted_opt="$((idx + 1)) \t $opt"
            local formatted_opt=$(echo "$formatted_opt" | cut -c1-$((max_width - 3)))
            if [ $idx -eq $selected ]; then
                print_selected "$formatted_opt"
            else
                print_option "$formatted_opt"
            fi
            ((idx++))
        done

        # User key control
        case `key_input` in
            enter) break;;
            up)    ((selected--));
                   if [ $selected -lt 0 ]; then selected=$(($# - 1)); fi;;
            down)  ((selected++));
                   if [ $selected -ge $# ]; then selected=0; fi;;
        esac
    done

    # Cursor position back to normal
    cursor_to $lastrow
    printf "\n"
    cursor_blink_on

    return $selected
}

# Echo with colors
colorecho() {
    color="$1"
    text="$2"
    [ -n "$no_warning" ] && [ "$color" = "$YELLOW" ] || [ "$color" = "$DEBUG" ] && [ -z "$debug_log" ] || echo -e "${color}${text}${NC}"
}

# Title / Heading
title() {
  clear
  text="$1"
  echo "---------------------------------------------------------------------"
  colorecho "$BLUE" "${text}"
  echo "---------------------------------------------------------------------"
}

titlelogo() {
  clear
  echo "---------------------------------------------------------------------"
  colorecho "$BLUE" "                  ##                     __   ____  _  _    "
  colorecho "$BLUE" "                 ####                   / _\ (  _ \( \/ )   "
  colorecho "$BLUE" "                ######                 /    \ )   // \/ \ "
  colorecho "$BLUE" "               ########                \_/\_/(__\_)\_)(_/ "
  colorecho "$BLUE" "              ##########          ___  __   __ _  ____  __  ___ "
  colorecho "$BLUE" "             ############        / __)/  \ (  ( \(  __)(  )/ __)"
  colorecho "$BLUE" "            ##############      ( (__(  O )/    / ) _)  )(( (_ \ "
  colorecho "$BLUE" "           ################      \___)\__/ \_)__)(__)  (__)\___/"
  colorecho "$BLUE" "          ######      ######           _  _  ____  __  __   "
  colorecho "$BLUE" "         #######      #######         / )( \(_  _)(  )(  )  "
  colorecho "$BLUE" "       #######         #######        ) \/ (  )(   )( / (_/\ "
  colorecho "$BLUE" "      ######             ######       \____/ (__) (__)\____/ "
  colorecho "$BLUE" "     ###                     ###    "
  echo "---------------------------------------------------------------------"
  if [ -n "$1" ]; then
    text="$1"
    colorecho "$BLUE" "${text}"
    echo "---------------------------------------------------------------------"
  fi
}

################################################################
# Version updates handling

# Check updates
check_util_updates() {
    # Install git if not installed
    if ! command -v git &> /dev/null; then
        colorecho "$YELLOW" "Installing git ..."
        sudo pacman -S git --needed --noconfirm
    fi
    if [ "$release" == "dev" ]; then
        remote_release="dev"
    elif [[ "$release" == *"-dev"* ]]; then
        remote_release=$(git ls-remote --tags $remote_repo | sort -Vr -k2 | grep -Po -m 1 "tags/\K.*..*..*")
    else
        remote_release=$(git ls-remote --tags $remote_repo | grep -v "dev" | sort -Vr -k2 | grep -Po -m 1 "tags/\K.*..*..*")
    fi
    if [ "$(echo "$remote_release" | sed 's/-.*//' | tr -d '.')" -gt "$(echo "$release" | sed 's/-.*//' | tr -d '.')" ]; then
        update_available=true
    fi
}

# Install / Update Utility to PATH
update_util() {
    if [ "$update_available" = true ] || [ -n "$argupdate" ]; then
        titlelogo
        colorecho "$GREEN" "Installing / Updating $utilname ..."
        local response_code=$(sudo curl --write-out '%{response_code}' -o /usr/bin/acu -L "https://raw.githubusercontent.com/kwankiu/acu/$remote_release/acu")
        sudo chmod +x /usr/bin/acu
        if [ "$response_code" = 200 ]; then
            local config_dir=$(dirname "$config_file")
            if [ -z "$no_config_update" ]; then
                colorecho "$DEBUG" "Renaming existing config.yaml to config.old ..."
                mv "$config_file" "$config_dir/config.old"
            fi
        else
            colorecho "$RED" "Error: failed to install / update $utilname. Check your internet or user permissions."
            exit 1
        fi
        args=("$@")
        for ((i = 0; i < ${#args[@]}; i++)); do
            if [[ "${args[i]}" == "-u" || "${args[i]}" == "--update" ]]; then
                unset 'args[i]'  # Remove -y or --yes from the arguments
            fi
        done
        acu "${args[@]}"
        exit 0
    fi
}

# Create an alias of acu or another command
add_alias() {
    # Path to the directory where the alias script will be created
    ALIAS_SCRIPT_DIR="/usr/bin"

    # Alias name
    ALIAS_NAME=$1

    # Command to run
    if [ -z "$2" ]; then
        COMMAND_TO_RUN="acu"
    else
        COMMAND_TO_RUN="${@:2}"
    fi

    # Create the alias script
    sudo bash -c "echo '#!/bin/bash' > $ALIAS_SCRIPT_DIR/$ALIAS_NAME"
    sudo bash -c "echo '$COMMAND_TO_RUN \"\$@\"' >> $ALIAS_SCRIPT_DIR/$ALIAS_NAME"
    sudo chmod +x $ALIAS_SCRIPT_DIR/$ALIAS_NAME
    colorecho "$GREEN" "Command '$ALIAS_NAME' has been created."
}

################################################################
# Packages Install Tools

install_from_source() {
    
    if [ "$(id -u)" -eq 0 ]; then
        colorecho "$RED" "Error: acu is running in root or sudo, the following command can not be executed."
        exit 1
    fi
    # Install required package    
    sudo pacman -Sy --needed git base-devel --noconfirm
    
    # Ensure folder doesn't exist
    sudo rm -rf "$source_repo_dir"
    
    # Get the repository URL from the argument
    repo_url="$1"
    
    # If the URL starts with 'aur://', modify the URL to use AUR repository
    if [[ "$repo_url" == aur://* ]]; then
        package_name="${repo_url#aur://}"
        repo_url="https://aur.archlinux.org/$package_name.git"
    # If the URL starts with 'gh://', modify the URL to use GitHub repository
    elif [[ "$repo_url" == gh://* ]]; then
        ghrepo_name="${repo_url#gh://}"
        repo_url="https://github.com/$ghrepo_name.git"
    fi
    
    # Clone repo
    colorecho "$GREEN" "Cloning Package from source ..."

    if [ -z "$git_branch" ]; then
        git clone "$repo_url" "$source_repo_dir"
    else
        git clone "$repo_url" "$source_repo_dir" -b $git_branch
        git_branch="" # this unsets the branch variable
    fi
    
    # Compile & Install
    cd "$source_repo_dir"
    
    if [ ! -z "$2" ] && [ "$2" != "--noinstall" ]; then
        cd "$2"
    fi
    
    colorecho "$GREEN" "Compiling & Installing Package from source ..."
    if [ -z "$no_confirm" ]; then
        makepkg -sA
    else
        makepkg -sA --noconfirm
    fi

    if [ "$2" != "--noinstall" ] && [ "$3" != "--noinstall" ]; then
        if [ -z "$no_confirm" ]; then
            sudo pacman -U *.pkg.tar.*
        else
            sudo pacman -U *.pkg.tar.* --noconfirm
        fi
    
        # Clean Up
        cd $HOME
        sudo rm -rf "$source_repo_dir"
    fi 

}

# Install Single Packages from any URL
install_pkg_from_url() {
    colorecho "$GREEN" "Downloading package from $1 ..."
    curl -LJO $1
    ipkgname=$(basename $1)
    colorecho "$GREEN" "Installing package $ipkgname ..."
    if [ -z "$no_confirm" ]; then
        sudo pacman -U $ipkgname
    else
        sudo pacman -U $ipkgname --noconfirm
    fi
    rm -rf $ipkgname
}


# Get available repo of GitHub Organizations
get_ghapi_orgs() {
    local selection
    if [ -z "$1" ]; then
        colorecho "$RED" "Error: No url specified."
        exit 1
    else
        apiurl=$1
    fi
    
    ghrel_url=("$apiurl")
    dgpkg_list=()

    for which_url in "${ghrel_url[@]}"; do
      dgpkg_list+=($(curl -s "${which_url}?per_page=100" | grep -oP '"full_name": "(?!.*/\.)\K[^"]+'))
    done

    ghapi_pkg_results=()
    for url in "${dgpkg_list[@]}"; do
        selection=$(basename "$url")
        ghapi_pkg_results+=("$selection")
    done
}

# Download Packages from a GitHub Release Repo
install_ghrel_packages() {
    local selection
    if [ -z "$1" ]; then
        colorecho "$RED" "Error: No package specified."
        exit 1
    else
        dgpkg=$1
    fi
    
    ghrel_url=("$adrepo_url")
    dgpkg_list=()

    for which_url in "${ghrel_url[@]}"; do
      colorecho "$GREEN" "Fetching $which_url ..."
      dgpkg_list+=($(curl -s "$which_url" | grep -v '.sig' | grep -B 1 ${dgpkg} | grep -oP '"browser_download_url": "\K[^"]+'))
    done

    echo ""
    colorecho "$BLUE" "The following packages will be downloaded:"
    echo ""
    for url in "${dgpkg_list[@]}"; do
        selection=$(basename "$url")
        echo "$selection"
    done
    echo ""
    echo -ne $"${BLUE}Are you sure to download the packages (y/n)?${NC}"
    read answer

    if [ "$answer" = "y" ]; then
        for url in "${dgpkg_list[@]}"; do
            selection=$(basename "$url")
            echo "Downloading and Installing $selection ..."
            install_pkg_from_url "$url"

            if [ ! -z "$2" ]; then
              sudo cp -r $selection $2/$selection
              sudo rm -rf $selection
            fi

        done
    fi

}

################################################################
# ACU File Pre-Parser
# source: https://github.com/mrbaseman/pasrse_yaml.git
# awk : process multi-line text (handle YAML pipe) (added a space for better syntax / readability)
# sed : replace '-' with a space
pre_parser() {
    local indexfix=-1
    local target_file=$1

    # Handle URL
    if [[ "$target_file" == *"://"* ]]; then
        local temp_file=$(mktemp)
        curl -s "$target_file" > "$temp_file"
        target_file="$temp_file"
    fi

    # Detect awk flavor
    if awk --version 2>&1 | grep -q "GNU Awk" ; then
        # GNU Awk detected
        indexfix=-1
    elif awk -Wv 2>&1 | grep -q "mawk" ; then
        # mawk detected
        indexfix=0
    fi

    local s='[[:space:]]*' sm='[ \t]*' w='[a-zA-Z0-9_.]*' fs=${fs:-$(echo @|tr @ '\034')} i=${i:-  }

    cat $target_file | \
    awk -F$fs "{multi=0;
        if(match(\$0,/$sm\|$sm$/)){multi=1; sub(/$sm\|$sm$/,\" \");}
        if(match(\$0,/$sm>$sm$/)){multi=2; sub(/$sm>$sm$/,\" \");}
        while(multi>0){
            str=\$0; gsub(/^$sm/,\"\", str);
            indent=index(\$0,str);
            indentstr=substr(\$0, 0, indent+$indexfix) \"$i\";
            obuf=\$0;
            getline;
            while(index(\$0,indentstr)){
                obuf=obuf substr(\$0, length(indentstr)+1);
                if (multi==1){obuf=obuf \"\\\\n\";}
                if (multi==2){
                    if(match(\$0,/^$sm$/))
                        obuf=obuf \"\\\\n\";
                        else obuf=obuf \" \";
                }
                getline;
            }
            sub(/$sm$/,\"\",obuf);
            print obuf;
            multi=0;
            if(match(\$0,/$sm\|$sm$/)){multi=1; sub(/$sm\|$sm$/,\"\");}
            if(match(\$0,/$sm>$sm$/)){multi=2; sub(/$sm>$sm$/,\"\");}
        }
    print}" | \
    sed 's/^\( *\)-/\1 /'

    # Remove the temporary file if it was created
    if [[ -n $temp_file ]]; then
        rm "$temp_file"
    fi
}

# ACU File Parser
# Limitation: this is not a full YAML parser, it is only designed to properly handle upto two sub-tree (subhead)
# Limitation: an unnecessary space at line ending can potentially cause issues
load_yaml() {
    local target_file=$1
    local suffix=$2
    local current_head=""
    local current_subhead=""
    local last_indent=""
    target_file="$(pre_parser "$target_file")"
    if [ -f "$target_file" ] || [[ "$target_file" == *"://"* ]] ; then
        while IFS= read -r line; do
            # Ignore comments and empty lines
            if ! [[ $line =~ ^[[:space:]]*($|#) ]]; then
                # Count indentation
                local indentation=$(expr "$line" : '^ *' / 2)
                # Remove indent spaces
                line="${line#"${line%%[![:space:]]*}"}"
                if [ "$indentation" = 0 ]; then
                    current_head="${line/:/}"
                elif [[ "$line" == *":"* ]]; then
                    if [ -z "$suffix" ]; then
                        # Use current head as suffix
                        current_value="${current_head}_${line//: /=\"}\""
                    elif [ "$suffix" != " " ]; then
                        # Use user specified suffix
                        current_value="${suffix}_${line//: /=\"}\""
                    else
                        # Set suffix to a space to set without suffix
                        current_value="${line//: /=\"}\""
                    fi
                    if [[ "$current_value" != *":\"" ]]; then
                        echo "$current_value"
                    else
                        current_subhead="${line/:/}"
                    fi
                elif [ "$indentation" -gt "$last_indent" ] || [ "$indentation" == "$last_indent" ]; then
                    current_value="${current_head}_${current_subhead}=\"${line}\""
                    echo "$current_value"
                else
                    colorecho "$DEBUG" "Indent: $indentation, Unhandled Line: $line"
                fi
                last_indent=$indentation
            fi
        done <<< "$target_file"
    fi
}

# Generate repo.yaml header
create_repo_yaml() {
    echo "#List of package repositories managed by acu" | tee "$repositories_file" >/dev/null
    echo "repositories:" | tee -a "$repositories_file" >/dev/null
    echo " " | tee -a "$repositories_file" >/dev/null

    echo "#- repo_name: example" | tee -a "$repositories_file" >/dev/null
    echo "#  repo_type: git #available types are agr, ghapi-orgs, ghapi-releases, and git." | tee -a "$repositories_file" >/dev/null
    echo "#  repo_url: https://example.com" | tee -a "$repositories_file" >/dev/null
    echo " " | tee -a "$repositories_file" >/dev/null
}

# Function to add a repository item to the YAML file
add_repository() {
    # Check if YAML file exists
    if [ ! -f "$repositories_file" ]; then
        # Create folder if it doesn't exist already
        mkdir -p "$(dirname "$repositories_file")"
        create_repo_yaml
    fi
    # Read repository name
    if [ -z "$1" ]; then
        read -p "Enter repository name: " repo_name
    else
        repo_name="$1"
    fi

    # Read repository URL
    if [ -z "$2" ] || [[ "$2" == "--"* ]]; then
        if [ "$1" = "acu" ]; then
            if [ -z "$git_branch" ]; then
                git_branch="pkgbuilds"
            fi
            repo_url="https://github.com/kwankiu/acu"
        else
            read -p "Enter repository URL: " repo_url
        fi
    else
        repo_url="$2"
    fi

    # Validate and auto-detect repository type based on URL format
    if [[ "$repo_url" == "https://api.github.com/orgs"* ]]; then
        repo_type="ghapi-orgs"
    elif [[ "$repo_url" == "https://api.github.com/repos"* ]]; then
        repo_type="ghapi-releases"
    elif [[ "$repo_url" == "http://"*"/"*"/"* || "$repo_url" == "https://"*"/"*"/"* ]]; then
        repo_type="agr"
        if [ -n "$git_branch" ]; then
            repo_url="$repo_url:$git_branch"
        fi
    elif [[ "$repo_url" == "http://"* || "$repo_url" == "https://"* ]]; then
        repo_type="git"
    else
        echo "Invalid repository URL format."
        return
    fi

    # Append new repository item to YAML file
    echo "- repo_name: $repo_name" | tee -a "$repositories_file" >/dev/null
    echo "  repo_type: $repo_type" | tee -a "$repositories_file" >/dev/null
    echo "  repo_url: $repo_url" | tee -a "$repositories_file" >/dev/null
    echo " " | tee -a "$repositories_file" >/dev/null

    echo "Repository added successfully."
}

# Function to load repositories into arrays
load_repositories() {
    # Initialize arrays for storing repository information
    repo_names=()
    repo_types=()
    repo_urls=()

    # Read repositories from YAML file
    if [ -f "$repositories_file" ]; then
        while IFS= read -r line; do
            # Ignore lines starting with '#'
            if [[ $line != "#"* ]]; then
                if [[ $line == *"repo_name"* ]]; then
                    repo_name=$(echo "$line" | awk '{print $3}')
                    repo_names+=("$repo_name")
                elif [[ $line == *"repo_type"* ]]; then
                    repo_type=$(echo "$line" | awk '{print $2}')
                    repo_types+=("$repo_type")
                elif [[ $line == *"repo_url"* ]]; then
                    repo_url=$(echo "$line" | awk '{print $2}')
                    repo_urls+=("$repo_url")
                fi
            fi
        done < "$repositories_file"
    fi
}

# Function to list repositories sorted by type
list_repositories() {
    load_repositories

    # Print repositories
    echo "List of Repositories:"
    for ((i = 0; i < ${#repo_names[@]}; i++)); do
        echo "  Name: ${repo_names[i]}"
        echo "  Type: ${repo_types[i]}"
        echo "  URL: ${repo_urls[i]}"
    done
}

# Function to list repositories sorted by type
remove_repository() {
    load_repositories
    local toremove=$1

    colorecho "$RED" "Are you sure to remove repository $toremove ? [y/N]:" 
    read -r delrepoconfirm
    case "$delrepoconfirm" in
        [yY])
            echo "Removing repository $toremove ..."
            sudo rm -rf $repositories_file
            ;;
        *)
            echo "Repository will not be removed."
            exit 1
            ;;
    esac

    # Print repositories
    echo "Generating new repository configuration ..."
    create_repo_yaml
    for ((i = 0; i < ${#repo_names[@]}; i++)); do
        # Append new repository item to YAML file
        if [ "$toremove" != "${repo_names[i]}" ]; then
            acu rem set ${repo_names[i]} ${repo_urls[i]}
        else
            if [ "${repo_types[i]}" == "agr" ]; then
                echo "Removing ${repo_names[i]} from agr ..."
                agr rem del ${repo_names[i]}
            fi
            echo "removed ${repo_names[i]} successfully."
        fi
    done
}

# Function to fetch packages of a repositories
fetch_repositories() {
    load_repositories
    echo ":: Fetching package repositories..."

    for ((i = 0; i < ${#repo_names[@]}; i++)); do
        echo -n "${repo_names[i]}"
        printf "\t\t [ ########################## ] \t"
        case ${repo_types[i]} in
            agr)
                if ! command -v agr &> /dev/null; then
                    # Install AGR if not installed
                    colorecho "$RED" "This repository requires agr to be installed, do you want to install it? [y/N]:" 
                    read -r agrconfirm
                    case "$agrconfirm" in
                        [yY])
                            acu install agr --noconfirm
                            ;;
                        *)
                            colorecho "$YELLOW" "WARNING $NC | This repository will be skipped and will not be fetched."
                            ;;
                    esac
                fi
                if command -v agr &> /dev/null; then
                # Extract the branch name using parameter expansion and pattern matching
                    if [[ "${repo_urls[i]}" == *"://"*"/"*"/"*":"* ]]; then
                        local agr_url="${repo_urls[i]%:*}"
                        local agr_branch="${repo_urls[i]##*:}"  # Remove everything up to the last ":"
                        agr rem set "${repo_names[i]}" "$agr_url" --branch "$agr_branch"
                    else
                        agr rem set "${repo_names[i]}" "${repo_urls[i]}"
                    fi
                    if [ -n "$debug_log" ]; then
                        agr -d 2>&1
                    else
                        agr 2>&1
                    fi
                fi
                ;;
            ghapi-orgs)
                colorecho "$BLUE" "INFO $NC | Looking up remote: ${repo_urls[i]}"
                get_ghapi_orgs ${repo_urls[i]}
                for pkg in "${ghapi_pkg_results[@]}"; do
                    colorecho "$BLUE" "      PKG$NC |     $pkg"
                done
                colorecho "$BLUE" "      INFO$NC|"
                colorecho "$BLUE" "      INFO$NC|     found ${#ghapi_pkg_results[@]} packages"
                ;;
            ghapi-releases)
                colorecho "$BLUE" "INFO $NC | Looking up remote: ${repo_urls[i]}"
                adrepo_url=${repo_urls[i]}
                ghapi_pkg_results=($(echo -e "n" | install_ghrel_packages .pkg.tar. | grep .pkg.tar.* | sed 's/\.pkg\..*//'))
                for pkg in "${ghapi_pkg_results[@]}"; do
                    colorecho "$BLUE" "      PKG$NC |     $pkg"
                done
                colorecho "$BLUE" "      INFO$NC|"
                colorecho "$BLUE" "      INFO$NC|     found ${#ghapi_pkg_results[@]} packages"
                ;;
            git)
                colorecho "$BLUE" "INFO $NC | Looking up remote: ${repo_urls[i]}"
                if curl -s --head ${repo_urls[i]} &> /dev/null; then
                    colorecho "$GREEN" "      INFO$NC |     Successfully fetched host. Packages list fetching unsupported, skipping ..."
                else
                    colorecho "$RED" "      INFO$NC |     Error: failed to resolve host."
                fi
                ;;
            *)
                colorecho "$BLUE" "INFO $NC | Looking up remote: ${repo_urls[i]}"
                colorecho "$RED" "      INFO$NC |     Error: invalid repository type. Valid types are: agr, ghapi-orgs, ghapi-releases, git."
                return
                ;;
        esac

    done
}

################################################################
# Utility Main Menu

config_options() {
    titlelogo
    options=("System Maintenance \t Managing Updates, Bootloader, System, Linux Kernel")
    options+=("Manage Packages \t Upgrade or downgrade packages, Manage packages repositories")
    options+=("Install Apps \t\t Install New Software or Application packages")
    options+=("Performance \t\t Tweak SoC Performance Settings, Enable PWM Fan, Overclocking")
    options+=("Localization \t\t Generate locale, Install fonts, Set date, time & timezone")
    options+=("User Accounts \t\t Add, Remove or Change user account settings")

    if [ "$update_available" = true ]; then 
        options+=("Update Now $GREEN(Updates available)$NC Update Utility to latest version $GREEN($release -> $remote_release)$NC ")
    fi
    
    options+=("Exit Utility")
    select_option "${options[@]}"
    choice=$?

    # Choice
    case $choice in
        0)
            system_maintenance
            ;;
        1)
            manage_packages
            ;;
        2)
            install_packages
            ;;
        3)
            performance_features
            ;;
        4)
            localization
            ;;
        5)
            manage_user
            ;;
        6)
            update_util
            ;;
        *)
            exit 0
            ;;
    esac

}

################################################################
# System Maintenance

# System Maintenance Main Menu
system_maintenance() {
    titlelogo "System Maintenance"
    options=("Flash Bootloader \t Flash Bootloader to eMMC/TF Card/SPI Flash")
    options+=("Copy System \t\t Backup, Restore, or Clone this system with partimage")
    options+=("System Infomation \t Print infomation of this system / device")
    options+=("Return to Main Menu")
    select_option "${options[@]}"
    choice=$?

    # Choice
    case $choice in
        0)
            flash_uboot
            ;;
        1)
            if ! pacman -Q partimage; then
                echo "partimage is not installed"
                echo "Installing required package ..."
                acu install partimage
            fi
            sudo partimage
            ;;
        2)
            system_info
            ;;
        *)
            config_options
            ;;
    esac

}

# System Update
package_update() {

    titlelogo "Package Updates"

    if [ "$1" = "--select" ]; then
        local selected_option="${poptions[$2]}"

        if [[ " ${selection[*]} " == *" $selected_option "* ]]; then
            options[$2]="[ ] ${selected_option}"
            selection=("${selection[@]/$selected_option}")
        else
            options[$2]="[x] ${selected_option}"
            selection+=("$selected_option")
        fi
    else
        selection=()
        options=("Return to Main Menu" "Upgrade All Packages" "Upgrade Selected Packages")
        options+=("$GREEN----------------------------------------------------" "$GREEN Upgradable Packages (Press enter to select/deselect): " "$GREEN----------------------------------------------------" "Refresh / Reset $NC")
        poptions=("${options[@]}")

        if [ -x "$(command -v yay)" ]; then
            update_list=($(yay -Qu))
            if [ -z "$update_list" ]; then
                options[6]="Refresh / Reset $NC (All packages are up-to-date)"
            else
                for ((i=0; i<${#update_list[@]}; i+=4)); do
                    options+=("[ ] ${update_list[i]}")
                    poptions+=("${update_list[i]}")
                done
                options[6]="Refresh / Reset $NC (Using yay)"
            fi
        else
            update_list=($(pacman -Qu | awk -F' ' '{ if (NF == 4) { $5 = "[]" } }1'))
            if [ -z "$update_list" ]; then
                options[6]="Refresh / Reset $NC (All packages are up-to-date)"
            else
                for ((i=0; i<${#update_list[@]}; i+=5)); do
                    options+=("[ ] ${update_list[i]}")
                    poptions+=("${update_list[i]}")
                done
                options[6]="Refresh / Reset $NC (Using pacman)"
            fi
        fi
    fi

    select_option "${options[@]}"
    choice=$?

    if [ "$choice" = "0" ]; then
        config_options
    elif [ "$choice" = "1" ]; then
        if [ -x "$(command -v yay)" ]; then
            yay -Syyu
        else
            if [ -z "$no_confirm" ]; then
                sudo pacman -Syyu
            else
                sudo pacman -Syyu --noconfirm
            fi
        fi
    elif [ "$choice" = "2" ]; then
        if [ -x "$(command -v yay)" ]; then
            yay -S "${selection[*]}"
        else
            if [ -z "$no_confirm" ]; then
                sudo pacman -Sy "${selection[*]}"
            else
                sudo pacman -Sy "${selection[*]}" --noconfirm
            fi
        fi
    elif [ "$choice" = "3" ] || [ "$choice" = "4" ] || [ "$choice" = "5" ] || [ "$choice" = "6" ]; then
        package_update
    else
        package_update --select $choice
    fi

}

# Update Bootloader
flash_uboot() {

        if [ -z "$1" ]; then
            titlelogo "Flash Bootloader"
            colorecho "$GREEN" "Select an option to confirm"
            colorecho "$RED" "Warning : The SPI NOR flash will be cleared."
            echo ""
            if [ -e /dev/mtdblock0 ]; then
                colorecho "$RED" "Show U-Boot"
            elif [ -e /dev/nvme* ]; then
                colorecho "$RED" "Show NVMe"
            fi
            echo "Coming Soon"
            options=("Return to System Maintence Menu")
            select_option "${options[@]}"
            choice=$?
        else
            case $1 in
                *)
                    system_maintenance
                    ;;
            esac
        fi

        # Choice
        case $choice in
            0)
                # Fetch the HTML content of the URL and extract the latest image filename
                which_url=$uboot_url
                colorecho "$GREEN" "Fetching latest Radxa U-Boot Image ..."
                latest_image=$(curl -s "$which_url" | grep -o 'rock-5b-spi-image-[a-z0-9-]*\.img' | head -n 1)
                ;;
            1)
                # Fetch the HTML content of the URL and extract the latest image filename
                which_url=$uboot_debug_url
                colorecho "$GREEN" "Fetching latest Radxa U-Boot (Debug Version) Image ..."
                latest_image=$(curl -s "$which_url" | grep -o 'rock-5b-spi-image-[a-z0-9-]*\-debug.img' | head -n 1)
                ;;
            2)
                # Fetch the HTML content of the URL and extract the latest image filename
                which_url=$edk2_url
                colorecho "$GREEN" "Fetching EDK2 Bootloader (UEFI) ..."
                latest_image=$(curl -s "$which_url" | grep -wo "https.*rock-5a.*\.img" | head -n 1)
                which_url="$(dirname "$latest_image")/"
                latest_image=$(basename "$latest_image")
                ;;
            3)
                # Fetch the HTML content of the URL and extract the latest image filename
                which_url=$edk2_url
                colorecho "$GREEN" "Fetching EDK2 Bootloader (UEFI) ..."
                latest_image=$(curl -s "$which_url" | grep -wo "https.*rock-5b.*\.img" | head -n 1)
                which_url="$(dirname "$latest_image")/"
                latest_image=$(basename "$latest_image")
                ;;
            4)
                # Fetch the HTML content of the URL and extract the latest image filename
                which_url=$armbian_url
                colorecho "$GREEN" "Fetching Armbian Bootloader ..."
                latest_image=$(basename "$which_url")
                which_url="$(dirname "$which_url")/"
                ;;
            *)
                exit 0
                ;;
        esac

    ###
    colorecho "$GREEN" "Install bootloader to the SPI NOR flash ..."
    exit 1


    colorecho "$GREEN" "Downloading Zero Image ..."
    curl -LJO ${zero_url}

    if ! [ -x "$(command -v gzip)" ]; then
        sudo pacman -Sy gzip --noconfirm
    fi

    colorecho "$GREEN" "Extracting Zero Image ..."
    gzip -d zero.img.gz

    colorecho "$GREEN" "Flashing Zero Image to SPI NOR flash ..."
    sudo dd if=zero.img of=/dev/mtdblock0

    # Remove zero.img
    sudo rm -rf zero.img

    if [ -n "$latest_image" ]; then
        # Download the latest image
        colorecho "$GREEN" "Downloading SPI U-Boot Image from ${which_url}${latest_image} ..."
        curl -LJO ${which_url}${latest_image}
    else
        colorecho "$RED" "Fetch Error : No image found."
        sleep 1
        exit 1
    fi
    
    colorecho "$GREEN" "Flashing SPI U-Boot Image ${latest_image} to SPI NOR flash ..."
    sudo dd if=${latest_image} of=/dev/mtdblock0
    sync
    colorecho "$GREEN" "Installed bootloader to SPI NOR flash"

    # Remove u-boot image file
    sudo rm -rf ${latest_image}

}

# Re-install Kernel
update_kernel_extlinux() {

    # Update extlinux.conf
    colorecho "$YELLOW" "Generating extlinux.conf for $1..."

    if ! sudo pacman -Q $1 ; then
        colorecho "$RED" "provided package may not be installed, extlinux.conf will not be updated ..."
        sudo cp -r /etc/mkinitcpio.old/* /etc/mkinitcpio.d
        sudo rm -rf /etc/mkinitcpio.old
        exit 1
    fi

    if sudo test -e  "/boot/extlinux/extlinux.arch.template"; then 
        colorecho "$YELLOW" "Using extlinux.arch.template ..."
        sudo mv /boot/extlinux/extlinux.arch.template /boot/extlinux/extlinux.conf
    elif [ -n "$device_config" ] && [ -e /boot/vmlinuz-$1 ]; then
        # Kernel does not provide template, get sbc template
        colorecho "$YELLOW" "Downloading extlinux template for ${device_config} ..."
        curl -LRO https://github.com/kwankiu/archlinux-installer-rock5/releases/download/kernel/${device_config}.extlinux.template
        sudo mv ${device_config}.extlinux.template /boot/extlinux/extlinux.conf
    else
        echo "No available template, skipping ..."
        colorecho "$YELLOW" "Warning: You may need to update extlinux.conf before booting into the new kernel."
        exit 0
    fi        
        
    colorecho "$YELLOW" "Generating extlinux.conf from template ..."
    # Get rootfs partition from the current mount point "/"
    rootfs_partition=$(mount | grep "on / " | awk '{print $1}')

    # Find the UUIDs of the root partition
    root_uuid=$(sudo blkid $rootfs_partition | awk '{print $2}' | tr -d '"')
    echo "Root partition UUID: $root_uuid"

    colorecho "$GREEN" "Updating extlinux.conf ..."

    # Change pkgbase for extlinux.conf
    if sudo test ! -e "/boot/dtbs/$1"; then 
        sudo sed -i "s|/dtbs/%PKGBASE%|/dtbs|" /boot/extlinux/extlinux.conf
    fi

    # fix rockchip overlay directory name
    if sudo test -e "/boot/dtbs/$1/rockchip/overlay"; then
        sudo sed -i "s|/rockchip/overlays|/rockchip/overlay|" /boot/extlinux/extlinux.conf
    fi

    sudo sed -i "s|%PKGBASE%|$1|" /boot/extlinux/extlinux.conf

    # Change UUID for extlinux.conf   
    sudo sed -i "s|UUID=\\*\\*CHANGEME\\*\\*|$root_uuid|" /boot/extlinux/extlinux.conf
    sudo sed -i "s|UUID=CHANGEME|$root_uuid|" /boot/extlinux/extlinux.conf

    # Check if /boot is mounted as a partition or directory
    if mountpoint -q /boot; then
        colorecho "$GREEN" "/boot is mounted as a partition"
        colorecho "$GREEN" "Done"
    else
        colorecho "$GREEN" "/boot is mounted as a directory"
        colorecho "$GREEN" "Updating paths for extlinux.conf ..."
        sudo sed -i "s| /vmlinuz| /boot/vmlinuz|" /boot/extlinux/extlinux.conf
        sudo sed -i "s| /initramfs| /boot/initramfs|" /boot/extlinux/extlinux.conf
        sudo sed -i "s| /initrd| /boot/initrd|" /boot/extlinux/extlinux.conf
        sudo sed -i "s| /dtbs| /boot/dtbs|" /boot/extlinux/extlinux.conf
        sudo sed -i "s| /dtbo| /boot/dtbo|" /boot/extlinux/extlinux.conf
    fi

    sudo rm -rf /etc/mkinitcpio.old
}

# Move Arch Linux
move_system() {
    echo "Not implemented"
}

################################################################
# Manage Packages

# Manage Packages Main Menu
manage_packages() {
    titlelogo "Manage Packages"
    options=("Update Packages \t Check & Perform Selective / Full System Upgrade")
    options+=("Downgrade Packages \t Install / Downgrade any Arch Linux Packages from Archive")
    options+=("Add Pacman Repo \t Add a package repository to archlinux's package manager (pacman).")
    options+=("Add ACU Repo \t\t Add a package repository to be managed by acu.")
    options+=("Return to Main Menu")
    select_option "${options[@]}"
    choice=$?

    # Choice
    case $choice in
        0)
            package_update
            ;;
        1)
            downgrade_packages
            ;;
        2)
            add_repo
            ;;
        *)
            config_options
            ;;
    esac

}

# Install Packages
install_packages() {

    if [ "$launch_as_installer" = 1 ]; then
        title "Install Additional Packages"
    else
        titlelogo "Install / Update Software"
    fi

    category=("Web - Surf the Internet" "Communication - Connect with friends, family, teams" "Suites - Office & Productivity Software" "Multimedia - Audio, Video, Graphics Software" "Gaming / Emulation / Virtualization Software" "Development Tools - Editors, IDEs, Build Tools" "Misc - Firmware Driver, other Tools and Software")
    
    if [ "$launch_as_installer" = 1 ]; then
        options=("Finish Installation")
    else
        options=("Return to Main Menu")
    fi

    options+=("$GREEN----------------------------------------------------" "$GREEN Install / Update Software (Press enter to select/deselect): " "$GREEN----------------------------------------------------$GREEN")
    options+=("${category[@]}$NC")
    
    select_option "${options[@]}"
    choice=$?

    if [ "$choice" = "0" ]; then
        if [ "$launch_as_installer" = 1 ]; then
            colorecho "$GREEN" "Finishing installation ..."
        else
            config_options
        fi
    elif [ "$choice" = "1" ] || [ "$choice" = "2" ] || [ "$choice" = "3" ]; then
        install_packages
    else
        install_pkg_category $choice
    fi

}

install_pkg_category() {

    if [ "$1" = "--select" ]; then
        local selected_option="${poptions[$2]}"

        if [[ " ${selection[*]} " == *" $selected_option "* ]]; then
            options[$2]="[ ] ${selected_option}"
            echo "current list: ${selection[@]}"
            echo "try to remove ${selected_option%% *}"
        else
            options[$2]="[x] ${selected_option}"
            selection+=("${selected_option%% *}")
        fi
    else
        selection=()
        options=("Return to Category" "Install Selected Packages")
        options+=("$GREEN Deselect All $NC")
        poptions=("${options[@]}")

        case $1 in
            4)
                categorytitle="$utilname - Install Web"
                update_list=("firefox" "chromium" "ungoogled-chromium" "openssh" "nodejs" "nvm" "wget")
                ;;
            5)
                categorytitle="$utilname - Install Communication"
                update_list=("telegram-desktop" "teams" "discord" "silos")
                ;;
            6)
                categorytitle="$utilname - Install Suites"
                update_list=("libreoffice" "wps-office-cn" "abiword" "gnumeric" "gnucash" "glabels" "glom" "dia")
                ;;
            7)
                categorytitle="$utilname - Install Multimedia"
                update_list=("kodi" "vlc" "lollypop" "rhythmbox" "gimp" "inkscape" "krita" "audacity" "ardour" "blender")
                ;;
            8)
                categorytitle="$utilname - Install Gaming / Emulation / Virtualization"
                update_list=("box64" "box86" "steam" "malior" "malior-droid" "wine64" "qemu-full")
                ;;
            9)
                categorytitle="$utilname - Install Development Tools"
                update_list=("code" "sublime-text-4" "gedit" "vim" "gnome-console" "konsole" "xterm" "git" "python-pipx" "python2") 
                ;;
            10)
                categorytitle="$utilname - Install Misc"
                update_list=("intel-ax210-fw" "yay" "neofetch" "screenfetch" "s-tui" "stress")
                ;;
        esac
 
        for ((i=0; i<${#update_list[@]}; i++)); do
            options+=("[ ] ${update_list[i]}")
            poptions+=("${update_list[i]}")
        done
    fi

    titlelogo "$categorytitle"

    select_option "${options[@]}"
    choice=$?

    if [ "$choice" = "0" ]; then
        install_packages
    elif [ "$choice" = "1" ]; then
        #print_selected_pkg && exit 0
        install_selected_pkg
        install_packages
    elif [ "$choice" = "2" ]; then
        install_pkg_category
    else
        install_pkg_category --select $choice
    fi

}

print_selected_pkg() {
    colorecho "$GREEN" "Selected Packages :"
    for ((i=0; i<${#selection[@]}; i++)); do
        echo "${selection[i]}"
    done
}

install_selected_pkg() {

    for ((i=0; i<${#selection[@]}; i++)); do
        echo " Install ${selection[i]}"
        case ${selection[i]} in
            "chromium")
                if sudo pacman -Ssy "^chromium-mpp$" &> /dev/null; then
                    if [ -z "$no_confirm" ]; then
                        sudo pacman -Sy chromium-mpp
                    else
                        sudo pacman -Sy chromium-mpp --noconfirm
                    fi
                    #install_pkg_from_url "$alaa_url/packages/r/re2/re2-1%3A20230301-1-aarch64.pkg.tar.xz"
                    sudo systemctl enable --now libv4l-rkmpp-setup.service
                    # Check if the file /etc/chromium-browser exists
                    if [ ! -e "/etc/chromium-browser" ]; then
                        # Create the directory /etc/chromium-browser
                        sudo mkdir -p "/etc/chromium-browser"
                    fi
                    echo -e "# Default settings for chromium-browser. This file is sourced by /bin/sh from\n# /usr/bin/chromium-browser\n\n# Options to pass to chromium-browser\nLD_LIBRARY_PATH=/usr/lib/mali-valhall-g610/x11-wayland-gbm\nCHROMIUM_FLAGS=\"--use-gl=egl\"" | sudo tee /etc/chromium-browser/default >/dev/null
                else
                    if [ -z "$no_confirm" ]; then
                        sudo pacman -Sy chromium
                    else
                        sudo pacman -Sy chromium --noconfirm
                    fi
                fi
                ;;
            "nvm")
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
                export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
                source ~/.bashrc
                ;;
            "teams")
                install_from_source "aur://teams-for-linux-bin"
                ;;
            "discord")
                install_from_source "aur://armcord-bin"
                ;;
            "wine64")
                colorecho "$RED" "Warning: This is experimental."
                ;;
            "box86")
                colorecho "$YELLOW" "This is experimental."
                echo "Package Not Available, try update to latest utility."
                ;;
            "steam")
                acu install box86
                colorecho "$YELLOW" "Make sure you installed box86 before installing Steam. This is experimental."
                installSteam
                ;;
            "code")
                install_from_source "aur://visual-studio-code-bin"
                ;;
            "radxa-imager")
                install_from_source "gh://rock5-images-repo/radxa-imager"
                ;;
            "kodi")
                if sudo pacman -Ssy "^kodi-nexus-mpp-git$" &> /dev/null; then 
                    if [ -z "$no_confirm" ]; then
                        sudo pacman -Sy kodi-nexus-mpp-git
                    else
                        sudo pacman -Sy kodi-nexus-mpp-git --noconfirm
                    fi
                fi
                ;;
            "malior")
                bash <(curl -fsSL https://github.com/ChisBread/malior/raw/main/install.sh)
                malior update
                ;;
            "malior-droid")
                colorecho "$YELLOW" "Requires kernel with binderfs support"
                acu install wget docker android-tools scrcpy --noconfirm
                systemctl start docker --now
                echo "starting docker ..."
                sleep 3
                if ! command -v malior &> /dev/null; then
                    acu install malior
                fi
                sudo mkdir /dev/binderfs
	            sudo mount -t binder binder /dev/binderfs
	            malior install malior-droid
	            malior-droid update
                ;;
            "intel-ax210-fw")
                # wifi
                sudo curl -o /lib/firmware/iwlwifi-ty-a0-gf-a0-59.ucode https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/iwlwifi-ty-a0-gf-a0-59.ucode
                sudo mv /lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm /lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm.bak

                # bt
                sudo curl -o /lib/firmware/intel/ibt-0041-0041.sfi https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/intel/ibt-0041-0041.sfi
                sudo curl -o /lib/firmware/intel/ibt-0041-0041.ddc https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/intel/ibt-0041-0041.ddc
                ;;
            "yay")
                install_from_source "aur://yay-bin"
                ;;
            "agr")
                acu install python-pip --noconfirm
                python -m pip install https://github.com/hbiyik/agr/archive/master.zip --break-system-packages --force-reinstall
                sudo ln -s ~/.local/bin/agr /usr/local/bin/agr
                ;;
            *)
                # Handle Kernel Installation
                if [[ "${selection[i]}" == "linux-"* ]] || [[ "${selection[i]}" == *"://linux-"* ]] || [[ "${selection[i]}" == *"://"*"/linux-"* ]]; then
                    sudo rm -rf /etc/mkinitcpio.old
                    sudo cp -r /etc/mkinitcpio.d /etc/mkinitcpio.old
                    sudo rm -rf /etc/mkinitcpio.d/*
                fi

                # Handle URLs
                if [[ "${selection[i]}" == *"://"* ]]; then
                    use_pm="git"
                fi

                # Find and Install packages                    
                if [ "$use_pm" = "git" ]; then
                    colorecho "$GREEN" "Compling & Installing ${selection[i]} ..."   
                    install_from_source "${selection[i]}"
                elif [ "$use_pm" = "pacman" ] || ([ -z "$use_pm" ] && sudo pacman -Ssy "^${selection[i]}$" &> /dev/null); then
                    colorecho "$GREEN" "Installing ${selection[i]} with pacman ..."
                    if [ -z "$no_confirm" ]; then
                        sudo pacman -S ${selection[i]} 
                    else
                        sudo pacman -S ${selection[i]} --noconfirm
                    fi
                elif [ "$use_pm" = "agr" ] || ([ -z "$use_pm" ] && agr 2>&1 | grep -v -E '://' | grep -v 'INFO' | grep -q "${selection[i]}"); then
                    if [ "$(id -u)" -eq 0 ]; then
                        colorecho "$RED" "Error: acu is running in root or sudo, the following command can not be executed."
                        exit 1
                    fi
                    colorecho "$GREEN" "Compiling & Installing ${selection[i]} with agr ..."
                    if [ -z "$no_confirm" ]; then
                        agr install ${selection[i]} 
                    else
                        agr install ${selection[i]} --noconfirm
                    fi
                elif [ "$use_pm" = "adrepo" ] || ([ -z "$use_pm" ] && pkg_tar=($(echo -e "n" | install_ghrel_packages "${selection[i]}" | grep '.*pkg.*'))); then
                    colorecho "$GREEN" "Installing ${selection[i]} from adrepo ..."
                    install_ghrel_packages "${selection[i]}"
                elif aurrepo=$(git ls-remote "https://aur.archlinux.org/${selection[i]}") && [ -n "$aurrepo" ] ; then
                    colorecho "$GREEN"  "Compling & Installing ${selection[i]} from AUR ..."
                    install_from_source "aur://${selection[i]}"
                else
                    colorecho "$RED" "Error: package ${selection[i]} not found"
                fi

                # Handle Kernel Installation
                if [[ "${selection[i]}" == "linux-"* ]]; then
                    # Case 1: If it starts with "linux-", use it as is
                    update_kernel_extlinux "${selection[i]}"
                elif [[ "${selection[i]}" == *"://linux-"* ]]; then
                    # Case 2: If it contains "://linux-", remove everything before "://"
                    update_kernel_extlinux "${selection[i]##*://}"
                elif [[ "${selection[i]}" == *"://"*"/linux-"* ]]; then
                    # Case 3: If it contains "://" and "/linux-", take the part after "/linux-" and prepend "linux-"
                    update_kernel_extlinux "linux-${selection[i]#*"/linux-"}"
                fi
                ;;
        esac
    done
}

# Install Packages from Archive
downgrade_packages() {
    titlelogo "Downgrade Packages"

    if [ -z "$1" ]; then
        read -p "Enter package to downgrade: " dgpkg
    else
        dgpkg=$1
    fi

    if [ -z "$2" ]; then
        nopkg=15
    else
        nopkg=$2
    fi
    

    dgpkgfb=$(echo $dgpkg | cut -b 1)
    which_url="${alaa_url}packages/${dgpkgfb}/${dgpkg}/"
    colorecho "$GREEN" "Fetching $which_url ..."
    #latest_image=$(curl -s "$which_url" | grep -o '*-aarch64.pkg.tar.xz' | head -n 1)
    dgpkg_list=$(curl -s "$which_url" | grep -v '.sig' | grep -o 'href="[^"]*"' | sed 's/href="//;s/"$//' | grep -o ${dgpkg}.*-aarch64.pkg.tar.xz)
    dgpkg_date=$(curl -s "$which_url" | grep -v '.sig' | grep -o "${dgpkg}.*-aarch64.pkg.tar.xz.*<td class=\"date\">.*</td>" | grep -o "<td class=\"date\">.*</td>" | awk -F'<td class="date">|</td>' '{print $2}')

    #paste -d ' ' <(echo "$dgpkg_list") <(echo "$dgpkg_date") | sort -k 2,2 -r
    dgpkg_list=($(paste -d ' ' <(echo "$dgpkg_list") <(echo "$dgpkg_date") | sort -k 2,2 -r | awk '{print $1}' | head -n $nopkg))
    select_option "${dgpkg_list[@]}"
    choice=$?

    install_pkg_from_url ${which_url}${dgpkg_list[choice]}
}

add_repo() {
    if [ -z "$1" ]; then
        titlelogo "Add Pacman Repo"
        read -p "Enter repo name: " repo_name
        read -p "Enter server URL for $repo_name repo: " server_url
        read -p "Do you want to add a GPG key for $repo_name repo? [Y/n]: " add_gpg_key
        if [[ $add_gpg_key == [Yy]* ]]; then
            read -p "Enter GPG key for $repo_name repo: " gpg_key
        fi
    elif [ "$1" = "7Ji" ]; then
        server_url="https://github.com/7Ji/archrepo/releases/download/\$arch"
        gpg_key="BA27F219383BB875"
    elif [ "$1" = "BredOS" ]; then
        server_url="https://github.com/BredGang/bred-repo/raw/main/\$repo/\$arch"
    else
        colorecho "$RED" "Invalid repo name. Aborting."
        return 1
    fi

    if [ -z "$repo_name" ]; then
        repo_name="$1"
    fi

    colorecho "$GREEN" "Adding $repo_name to pacman.conf ..."

    if [ -z "$gpg_key" ]; then
        echo -e "[$repo_name]\nServer = $server_url" | sudo tee -a /etc/pacman.conf
    else
        echo -e "[$repo_name]\nSigLevel = Never\nServer = $server_url" | sudo tee -a /etc/pacman.conf
        colorecho "$GREEN" "Adding GPG keys ..."
        sudo pacman-key --recv-keys "$gpg_key"
        sudo pacman-key --lsign "$gpg_key"
    fi

    colorecho "$GREEN" "Updating repo ..."
    sudo pacman -Syy --noconfirm
    colorecho "$GREEN" "Done"
}

################################################################
# Performance & Features

# Performance & Features Main Menu
performance_features() {
    titlelogo "Performance & Features"
    options=("SoC Performance Profile \t Available options are performance, ondemand and powersave")
    options+=("PWM Fan Control \t\t (ROCK 5 ONLY) Configure PWM Fan-control service")
    #options+=("Overclocking - Configure rk3588-unlock-opps overlay which increases CPU supply & CPU VDD supply")
    #options+=("Overlay - Configure Device Tree Overlay")
    options+=("Return to Main Menu")
    select_option "${options[@]}"
    choice=$?

    # Choice
    case $choice in
        0)
            soc_profile
            ;;
        1)
            fan_control
            ;;
        #2)
            #overclocking
            #;;
        #3)
            #overlays
            #;;
        *)
            config_options
            ;;
    esac

}

system_info() {
    titlelogo "System Information"

    # Get OS
    sys_os=$(cat /etc/*-release | grep PRETTY_NAME | cut -d'"' -f2)

    # Get host / device model
    sys_host=$(cat /proc/device-tree/model | tr -d '\0')

    # Get kernel
    sys_krl=$(uname -sr)

    # Get uptime
    sys_uptime=$(uptime -p | sed 's/^up //')
    
    # Get cpu info
    sys_cpu=$(cat /proc/cpuinfo | grep -m1 "model name" | cut -d':' -f2 | sed 's/^ *//' | tr -d '\0')
    if [ -z "$sys_cpu" ] && [ -e "/proc/device-tree/compatible" ]; then
        sys_cpu_vendor=$(awk -F ',' '{print $1}' /proc/device-tree/cpuinfo/compatible | tr -d '\0' | sed 's/^\(.\)/\U\1/')
        sys_cpu_model=$(awk -F ',' '{print $NF}' /proc/device-tree/compatible | tr -d '\0' | tr '[:lower:]' '[:upper:]')
        sys_cpu=$(echo "$sys_cpu_vendor $sys_cpu_model")
    fi
    sys_cpu_thread=$(nproc)
    if [ -e "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq" ]; then
        sys_cpu_clock=($(sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq))
    else
        sys_cpu_clock="0.00"
    fi
    if [ -e "/sys/bus/cpu/devices/cpu0/cpufreq/scaling_governor" ]; then
        sys_cpu_governor=($(cat /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor))
    fi
    sys_arch=$(uname -m)

    # Get mem usage
    sys_mem_free=$(free -h | grep "Mem:" | awk '{print $4}' | sed 's\Gi\\g' | sed 's\Mi\\g')
    sys_mem_total=$(free -h | grep "Mem:" | awk '{print $2}' | sed 's\Gi\\g' | sed 's\Mi\\g')

    # Get disk usage
    sys_disk=$(df -h / | awk 'NR==2 {print $4" / "$2" ("$5")"}' | sed 's/G/ GiB/g; s/M/ MiB/g')

    # Get number of packages installed
    sys_packages=$(pacman -Q | wc -l)

    # Get shell
    sys_shell=$(basename "$SHELL")

    # Get graphics session
    if [ -n "$WAYLAND_DISPLAY" ]; then
        sys_session="Wayland"
    elif [ -n "$DISPLAY" ]; then
        sys_session="Xorg"
    fi

    # Get screen resolution
    if command -v xdpyinfo &> /dev/null; then
        sys_resolution=$(xdpyinfo | awk '/dimensions:/ {print $2}')
    else
        if [[ -d /sys/class/drm ]]; then
            for dev in /sys/class/drm/*/modes; do
                read -r single_resolution _ < "$dev"
                [[ $single_resolution ]] && sys_resolution="${single_resolution}"
            done
        fi
    fi

    # GPU Model
    if command -v glxinfo &> /dev/null; then
        sys_gpu=$(glxinfo | grep "OpenGL renderer string" | cut -d ":" -f 2 | cut -c 2-)
    else
        sys_gpu="Unknown (mesa-utils not installed)"
    fi

    # Get Desktop Environment
    sys_de=$(echo "$XDG_CURRENT_DESKTOP" | sed 's/.\+://')

    # Get terminal
    ppid=$(grep PPid: /proc/$$/status | awk '{print $2}')
    sys_terminal=$(basename $(cat "/proc/$ppid/comm"))
    if [ -n "$sys_session" ]; then
        while [ "$sys_terminal" == "watch" ] || [ "$sys_terminal" == "bash" ]; do
            ppid=$(grep PPid: /proc/${ppid}/status | awk '{print $2}')
            sys_terminal=$(basename $(cat "/proc/$ppid/comm"))
        done
    fi

    sys_terminal_font=$(basename "$TERM")

    colorecho "$BLUE" "OS: $NC $sys_os ($sys_arch)"
    colorecho "$BLUE" "Host: $NC $sys_host"
    colorecho "$BLUE" "Kernel: $NC $sys_krl"
    colorecho "$BLUE" "Uptime: $NC $sys_uptime"
    colorecho "$BLUE" "Packages: $NC $sys_packages"
    colorecho "$BLUE" "Shell: $NC $sys_shell"
    colorecho "$BLUE" "DE: $NC $sys_de ($sys_session)"
    colorecho "$BLUE" "Terminal: $NC $sys_terminal ($sys_terminal_font)"
    colorecho "$BLUE" "CPU: $NC ($sys_cpu_thread) $sys_cpu @ $(awk "BEGIN{printf \"%.2f\\n\", ((${sys_cpu_clock[4]:-${sys_cpu_clock[0]}}/1000000))}") Ghz (${sys_cpu_governor[4]:-${sys_cpu_governor[0]}})"
    colorecho "$BLUE" "GPU: $NC $sys_gpu"
    colorecho "$BLUE" "Resolution: $NC $sys_resolution"
    colorecho "$BLUE" "Memory: $NC $sys_mem_free GiB / $sys_mem_total GiB ($(awk "BEGIN{printf \"%.2f%%\\n\", (1-(${sys_mem_free}/${sys_mem_total}))*100}"))"
    colorecho "$BLUE" "Disk: $NC $sys_disk"
}

# SoC Performance Profile
soc_profile() {

    if [ -z "$1" ] || [ "$1" = "status" ]; then
        if [ -z "$1" ]; then
            titlelogo "SoC Performance Profile"
        else
            titlelogo "SoC Monitor"
        fi
        colorecho "$BLUE" "CPU Profile: $(cat /sys/bus/cpu/devices/cpu[046]/cpufreq/scaling_governor)"
        colorecho "$BLUE" "Memory Profile: $(cat /sys/class/devfreq/dmc/governor)"
        colorecho "$BLUE" "GPU Profile: $(cat /sys/class/devfreq/fb000000.gpu/governor)"
    fi

    if [ -z "$1" ]; then
        echo ""
        options=("Performance - Run SoC at full performance" "On Demand - Run SoC on CPU usage demand" "Power Save - Run SoC on Power Saving Mode" "Return to Main Menu")
        select_option "${options[@]}"
        choice=$?
    else
        case $1 in
                "performance")
                    choice=0
                    ;;
                "ondemand")
                    choice=1
                    ;;
                "powersave")
                    choice=2
                    ;;
                "status")
                    choice=99
                    ;;
                "force-performance")
                    force_performance_at_boot
                    choice=99
                    ;;
                *)
                    colorecho "$RED" "Invalid Option, Exiting ..."
                    exit 1
                    ;;
        esac
    fi

    if [ "$choice" = "0" ]; then
        echo performance | sudo tee /sys/bus/cpu/devices/cpu[046]/cpufreq/scaling_governor /sys/class/devfreq/dmc/governor /sys/class/devfreq/fb000000.gpu/governor
         colorecho "$GREEN" "Profile set to Performance"
    elif [ "$choice" = "1" ]; then
        echo ondemand | sudo tee /sys/bus/cpu/devices/cpu[046]/cpufreq/scaling_governor && echo dmc_ondemand | sudo tee /sys/class/devfreq/dmc/governor && echo simple_ondemand | sudo tee /sys/class/devfreq/fb000000.gpu/governor
        colorecho "$GREEN" "Profile set to On Demand"
    elif [ "$choice" = "2" ]; then
        echo powersave | sudo tee /sys/bus/cpu/devices/cpu[046]/cpufreq/scaling_governor /sys/class/devfreq/dmc/governor /sys/class/devfreq/fb000000.gpu/governor
        colorecho "$GREEN" "Profile set to Power Save"
    elif [ "$choice" = "99" ]; then
        fan_control status --soc-monitor
    else
        config_options
    fi

}

force_performance_at_boot() {
    echo -e "[Unit]\nDescription=Set Performance Mode on Boot\nAfter=multi-user.target\n\n[Service]\nType=oneshot\nExecStart=/bin/bash -c \"echo performance > /sys/bus/cpu/devices/cpu4/cpufreq/scaling_governor; echo performance > /sys/bus/cpu/devices/cpu0/cpufreq/scaling_governor; echo performance > /sys/bus/cpu/devices/cpu6/cpufreq/scaling_governor; echo performance > /sys/class/devfreq/dmc/governor; echo performance > /sys/class/devfreq/fb000000.gpu/governor\"\n\n[Install]\nWantedBy=multi-user.target" | sudo tee /etc/systemd/system/force-performance.service > /dev/null
    sudo systemctl daemon-reload
    sudo systemctl enable force-performance.service
}

################################################################
# Localization

# Localization Main Menu
localization() {
    titlelogo "Localization"
    options=("Locale \t\t Generate Locale Settings")
    options+=("Fonts \t\t\t Install Fonts, TTF, Non-English Characters, Special Characters / Emoji")
    options+=("Time \t\t\t Change Time Zone, Current Date and Time")
    options+=("Keyboard Layout \t Change Keyboard Layout")
    options+=("WiFi Country \t\t Change WiFi Country Settings")
    options+=("Return to Main Menu")
    select_option "${options[@]}"
    choice=$?

    # Choice
    case $choice in
        0)
            locale
            ;;
        1)
            fonts
            ;;
        2)
            timezone
            ;;
        3)
            keyboard
            ;;
        4)
            wifi_country
            ;;
        *)
            config_options
            ;;
    esac

}

# Function to manage user accounts
manage_user() {

    confirm_password() {
        while true; do
            read -s -p "Set a password for $new_user: " new_pw
            echo
            read -s -p "Confirm password for $new_user: " cfm_pw
            echo
            if [ "$new_pw" != "$cfm_pw" ]; then
                colorecho "$RED" "Password and confirm password does not match."
            elif [ -z "$new_pw" ] || [ -z "$cfm_pw" ]; then
                colorecho "$RED" "Password can not be empty."
            else
                return 0
            fi
        done
    }

    if [ -z "$1" ]; then
    titlelogo "Manage User"
    
    # List all user accounts
    real_users=($(getent passwd | awk -F: '$3 >= 1000 && $3 < 65534 {print $1}'))

    # Prompt to add a new user
    select_options=("Return to Main Menu" "Add User")
    select_options+=("${real_users[@]}")
    
    select_option "${select_options[@]}"
    choice=$?

    elif [ "$1" = "add" ]; then
        choice=1
        new_user=$2
        new_pw=$3
        cfm_pw=$3
    elif [ "$1" = "remove" ]; then
        choice=99
        t_user=$2
    elif [ "$1" = "manage" ]; then
        selected_user=$2
        manage_action=$3
    fi

    case $choice in
        0)
            config_options
            ;;
        1)
            if [ -z "$new_user" ]; then
                titlelogo "Add New User"
                read -p "Enter username for the new user: " new_user
            fi
            if [ -z "$new_pw" ]; then
                confirm_password
            fi
            sudo useradd -m "$new_user"
            echo -e "$new_pw\n$cfm_pw" | sudo passwd "$new_user"
            sudo usermod -aG wheel "$new_user"
            sudo usermod -aG video "$new_user"
            sudo usermod -aG audio "$new_user"
            sudo usermod -aG games "$new_user"
            sudo usermod -aG log "$new_user"
            sudo usermod -aG lp "$new_user"
            sudo usermod -aG optical "$new_user"
            sudo usermod -aG power "$new_user"
            sudo usermod -aG scanner "$new_user"
            sudo usermod -aG storage "$new_user"
            ;;
        99)
            if [ -z "$t_user" ]; then
                titlelogo "Remove User"
                read -p "Enter username to remove: " t_user
            fi            
             # Remove  account
            sudo userdel -r $t_user
            if [ $? -eq 0 ]; then
                echo "account removed successfully"
            else
                echo "Error removing account"
            fi
            ;;
        *)
            if [ -z "$selected_user" ]; then
                selected_user=${real_users[$((choice - 2))]}
            fi

            if [ -z "$manage_action" ]; then
                titlelogo "Manage $selected_user"
                colorecho "$GREEN" "User: $selected_user"
                echo ""

                # Perform actions for the selected user (if needed)
                options=("Return to Manage User Menu" "Change User Password")

                if sudo -lU "$selected_user" | grep NOPASSWD | grep -v -q "(root)"; then
                    options+=("Enable Sudo Password")
                else
                    options+=("Disable Sudo Password")
                fi

                if grep -qFx "$selected_user $hostname =NOPASSWD: /usr/bin/systemctl poweroff,/usr/bin/systemctl halt,/usr/bin/systemctl reboot" /etc/sudoers; then
                    options+=("Enable Reboot Password")
                else
                    options+=("Disable Reboot Password")
                fi

                select_option "${options[@]}"
                choice=$?
            elif [ "$manage_action" = "sudopw" ]; then
                choice=2
            elif [ "$manage_action" = "rebootpw" ]; then
                choice=3
            fi

            case $choice in
                0)
                    manage_user
                    ;;
                1)
                    sudo passwd "$selected_user"
                    ;;
                2)  
                    if sudo -lU "$selected_user" | grep NOPASSWD | grep -v -q "(root)"; then
                        sudo sed -i "s/^\($selected_user.*\)NOPASSWD: ALL/\1ALL/" /etc/sudoers
                        colorecho "$GREEN" "Enabled Sudo Password for $selected_user"
                    else
                        # NOPASSWD is not set, check if the user exists in sudoers file
                        if sudo grep -q "^[^#]*$selected_user ALL" /etc/sudoers; then
                            # User exists, change (ALL) ALL to (ALL) NOPASSWD: ALL
                            sudo sed -i "s/^\($selected_user.*\)(ALL) ALL/\1(ALL) NOPASSWD: ALL/" /etc/sudoers
                            echo "Changed $selected_user permissions to NOPASSWD: ALL"
                        else
                            # User does not exist, add it to sudoers file
                            echo "$selected_user ALL=(ALL) NOPASSWD: ALL" | sudo tee -a "/etc/sudoers" >/dev/null
                            echo "Added $selected_user to sudoers file with NOPASSWD: ALL"
                        fi
                        colorecho "$GREEN" "Disabled Sudo Password for $selected_user"
                    fi
                    ;;
                3)
                    local hostname=$(hostnamectl --static)
                    if grep -qFx "$selected_user $hostname =NOPASSWD: /usr/bin/systemctl poweroff,/usr/bin/systemctl halt,/usr/bin/systemctl reboot" /etc/sudoers; then
                        sudo sed -i "/^$selected_user $hostname =NOPASSWD: \/usr\/bin\/systemctl poweroff,\/usr\/bin\/systemctl halt,\/usr\/bin\/systemctl reboot$/d" /etc/sudoers
                        colorecho "$GREEN" "Enabled Reboot Password"
                    else
                        echo "$selected_user $hostname =NOPASSWD: /usr/bin/systemctl poweroff,/usr/bin/systemctl halt,/usr/bin/systemctl reboot" | sudo tee -a "/etc/sudoers" >/dev/null
                        colorecho "$GREEN" "Disabled Reboot Password"
                    fi
                    ;;
            esac
            ;;
    esac
}

# Function to select and generate locale
locale() {

    generated_locales=$(sudo locale -a)
    
    if [ -z "$1" ]; then
        titlelogo "Locale"
        
        # List available locales
        colorecho "$GREEN" "Generated Locales:"

        echo "$generated_locales"
        echo ""

        # Prompt to select and generate locale
        select_options=("Generate New Locales" "Return to Localization Menu")
        select_option "${select_options[@]}"
        choice=$?
    elif [ "$1" = "list-generated" ]; then
        echo "$generated_locales"
        exit 1
    elif [ "$1" = "list-available" ] || [ "$1" = "generate" ]; then
        choice=0
    else
        colorecho "$RED" "Invalid option"
        exit 1
    fi

    case $choice in
        0)
            # Read available locales from file and add numbers
            IFS=$'\n' read -d '' -ra locales <<< "$(grep -E '^#[^[:space:]]' /etc/locale.gen | sed 's/^#//')"
            IFS=$'\n' read -d '' -ra langcode <<< "$(grep -E '^#[^[:space:]]' /etc/locale.gen | sed 's/^#//; s/[ @.].*//' | uniq)"

            if [ ! "$1" = "list-available" ]; then

                if [ "$1" = "generate" ] && [ -z "$2" ] || [ "$1" = "locale" ] && [ -z "$2" ] || [ -z "$1" ]; then
                    colorecho "$GREEN" "Available Locales for generation:"

                    for ((i = 0; i < ${#langcode[@]}; i++)); do
                        echo "$((i + 1))) ${langcode[$i]}"
                    done

                    read -p "Enter the locale number: " chosen_number
                    chosen_locale=${langcode[$((chosen_number - 1))]}
                    colorecho "$GREEEN" "Picked $chosen_locale"
                else
                    chosen_locale=$2
                fi

                # Iterate through the array and find matches
                matches=()
                for ((i = 0; i < ${#locales[@]}; i++)); do
                    element="${locales[i]}"
                    if [[ "$element" =~ $chosen_locale ]]; then
                        matches+=("$element")
                    fi
                done
                
                titlelogo "Generate Locale"
                colorecho "$GREEN" "The following locales will be added:"

                for ((i = 0; i < ${#matches[@]}; i++)); do
                    echo "${matches[i]}"
                done

                if [ -z "$3" ]; then
                    select_options=("Generate Locales" "Cancel")
                    select_option "${select_options[@]}"
                    choice=$?
                elif [ "$3" = "-y" ]; then
                    choice=0
                else
                    colorecho "$RED" "Invalid option"
                    exit 1
                fi

                if [ "$choice" = 0 ]; then
                    for ((i = 0; i < ${#matches[@]}; i++)); do
                        sudo sed -i "s|#${matches[i]}|${matches[i]}|" /etc/locale.gen
                    done
                    sudo locale-gen
                fi
        
            else
                for ((i = 0; i < ${#langcode[@]}; i++)); do
                    echo "${langcode[$i]}"
                done
            fi
            ;;
        *)
            localization
            ;;
    esac
}

# Function to manage fonts
fonts() {
    titlelogo "Fonts"
    
    # Prompt to install fonts
    select_options=("Install Noto Fonts (including CJK and Emoji) - Support Asian Characters" "Install TTF Fonts from File" "Return to Localization Menu")
    select_option "${select_options[@]}"
    choice=$?

    case $choice in
        0)
            sudo pacman -Sy noto-fonts noto-fonts-cjk noto-fonts-emoji --noconfirm
            ;;
        1)
            read -p "Enter the path to the TTF font file: " font_path
            sudo cp "$font_path" /usr/share/fonts/TTF/
            sudo fc-cache -f -v
            ;;
        *)
            localization
            ;;
    esac
}

# Function to change time zone and date/time
timezone() {
    
    # Get current time zone and network time zone
    current_timezone=$(timedatectl show --property=Timezone --value)
    network_timezone=$(curl -s https://ipapi.co/timezone)


    if [ -z "$1" ]; then

        titlelogo "Time Zone"

        colorecho "$GREEN" "Network Time Zone: $network_timezone"

        if [ "$current_timezone" = "$network_timezone" ]; then
            colorecho "$GREEN" "Current Time Zone: $current_timezone"
        else
            colorecho "$RED" "Current Time Zone: $current_timezone"
        fi

        echo ""
        select_options=("Return to Localization Menu" "Set Time Zone Manually" "Set Date & Time Manually")

        if [ "$current_timezone" != "$network_timezone" ]; then
            select_options+=("Synchronize Time Zone with Network")
        fi

        select_option "${select_options[@]}"
        choice=$?
    
    elif [ "$1" = "set-time-zone" ]; then
        if [ -z "$2" ]; then
            choice=1
        elif [ "$2" = "sync" ]; then
            choice=3
        else
            choice=1
            new_timezone=$2
        fi
    elif [ "$1" = "set-time-date" ]; then
        choice=2
    elif [ "$1" = "network-time-zone" ]; then
        echo $network_timezone
    elif [ "$1" = "system-time-zone" ]; then
        echo $current_timezone
    fi

    case $choice in
        0)
            localization
            ;;
        1)
            if [ -z "$new_timezone" ]; then
                read -p "Enter new time zone (e.g., Asia/Tokyo): " new_timezone
            fi
            sudo timedatectl set-timezone "$new_timezone"
            echo "Time Zone updated to $new_timezone"
            sudo timedatectl set-ntp true
            ;;
        2)
            read -p "Enter the new date and time in format 'YYYY-MM-DD HH:MM:SS': " new_datetime
            sudo timedatectl set-time "$new_datetime"
            ;;
        3)
            sudo timedatectl set-timezone "$network_timezone"
            sudo timedatectl set-ntp true
            colorecho "$GREEN" "Time Zone synchronized with network."
            ;;
    esac
}

# Function to change keyboard layout
keyboard() {
    titlelogo "Keyboard Layout"

    # Get current keyboard layout
    current_layout=$(localectl status | grep "X11 Layout" | awk '{print $3}')
    
    echo "Current Keyboard Layout: $current_layout"
    
    # Prompt to select new keyboard layout
    select_options=("Change Keyboard Layout" "Return to Localization Menu")
    select_option "${select_options[@]}"
    choice=$?

    case $choice in
        0)
            read -p "Enter new keyboard layout (e.g., us, de): " new_layout
            sudo localectl set-x11-keymap "$new_layout"
            echo "Keyboard Layout updated to $new_layout"
            ;;
        *)
            localization
            ;;
    esac
}

# Function to change WiFi country
wifi_country() {
    titlelogo "WiFi Country"

    # Get available WiFi countries
    wifi_countries=("Return to Localization Menu")
    wifi_countries+=($(iw reg get | grep -o -E '^[A-Z]{2}'))
    
    # Display available WiFi countries and prompt to select
    select_option "${wifi_countries[@]}"
    choice=$?
    
    if [ "$choice" -ge 1 ] && [ "$choice" -le "${#wifi_countries[@]}" ]; then
        selected_country=${wifi_countries[$((choice))]}
        sudo iw reg set "$selected_country"
        echo "WiFi Country updated to $selected_country"
    else
        localization
    fi
}

################################################################
# Main Program

# NOTE that if new configurations (that arent optional / have a default value) are added, need to patch the existing user configurations file
# Load user configurations from YAML file
load_config() {
    if [ -f "$config_file" ] || [[ "$config_file" == *"://"* ]] ; then
        eval $(load_yaml "config/config.yaml" " ")
    elif [ ! "$(id -u)" -eq 0 ]; then
        # Download default configurations file
        local config_dir=$(dirname "$config_file")
        if [ -f "$config_dir/config.old" ]; then
            echo "Downloading new configuration file ..."
        else
            echo "No configuration file found, downloading configuration file ..."
        fi
        mkdir -p "$config_dir"
        response_code=$(curl --write-out '%{response_code}' -L https://raw.githubusercontent.com/kwankiu/acu/$release/config/config.yaml -o tmpdownload_config.yaml)
        if [ "$response_code" = 200 ]; then
            cp -r tmpdownload_config.yaml $HOME/.acu/config/config.yaml
            sudo rm -rf tmpdownload_config.yaml
            load_config
        else
            sudo rm -rf tmpdownload_config.yaml
        fi
    fi
}

print_config_values() {
    echo "Device Configuration: ${device_config:-"(unset)"}"
    echo "No Configuration Update: ${no_config_update:-"(unset)"}"
    echo "No Confirm: ${no_confirm:-"(unset)"}"
    echo "No Warning: ${no_warning:-"(unset)"}"
    echo "No Clear: ${no_clear:-"(unset)"}"
    echo "Debug Log: ${debug_log:-"(unset)"}"
    echo "Auto Update: ${auto_update:-"(unset)"}"
    echo "ALAA URL: ${alaa_url:-"(unset)"}"
    echo "Source Repo Dir: $HOME/${source_repo_dir:-"(unset)"}"
    echo "Repositories File: ${repositories_file:-"(unset)"}"
    echo "Repositories URL: ${repositories_url:-"(unset)"}"
    echo "Tags File: ${tags_file:-"(unset)"}"
    echo "Tags URL: ${tags_url:-"(unset)"}"
    echo "Kernel File: ${kernel_file:-"(unset)"}"
    echo "Kernel URL: ${kernel_url:-"(unset)"}"
    echo "Bootloader File: ${bootloader_file:-"(unset)"}"
    echo "Bootloader URL: ${bootloader_url:-"(unset)"}"
    echo "Apps File: ${apps_file:-"(unset)"}"
    echo "Apps URL: ${apps_url:-"(unset)"}"
}

# Handle arguments
for arg in "$@"; do
    case "$arg" in
        -d | --debug)
            debug_log=1
            ;;
        -v | --version)
            colorecho "$BLUE" "$utilname $release"
            colorecho "$DEBUG" "Build Number: $utilver"
            ;;
        -h | --help)
            colorecho "$BLUE" "$utilname $release"
            colorecho "$DEBUG" "Build Number: $utilver"
            echo
            colorecho "$GREEN" "Usage"
            echo
            echo "  acu : show interactive menu"
            echo "  acu <options> --flags : run commands"
            echo
            colorecho "$GREEN" "Options"
            echo
            echo "  -h / --help : Usage and Infomation of this configuration utility."
            echo "  -v / --version : Version of this configuration utility."
            echo "  -d / --debug : Show more logs, useful for debugging."
            echo "  -u / --update : Install / Update to latest configuration utility."
            echo "  -y / --yes : Automatically confirm y / yes for everything, not recommended for install command."
            echo "  --loadconfig=<path/url> : load an acu config file from path or url. (use with -u to install this config as default config file)"
            echo "  --update=<release> : Install / Update configuration utility to a specified release tag."
            echo "  --usepm=<pm> : Specify a package manager to use when installing packages. <pm> options: pacman, agr, git."
            echo "  --device=<tag> : Specify target device tag. <device> options are determined by the tags_file set in acu config."
            echo "  --branch=<branch> : Specify a git branch for setting or cloning from remote repository."
            echo "  --noconfirm : Do not ask for confirmation when resolving dependencies and installing packages managed by pacman / makepkg."
            echo "  --nowarning : Do not show warning messages."
            echo "  --noclear : Do not clear terminal output."
            echo "  --nowarning : Do not show warning messages."
            echo
            colorecho "$GREEN" "Features"
            echo
            colorecho "$BLUE" "System Maintenance"
            echo
            echo "  bootloader <bootloader> : Flash Bootloader to eMMC/TF Card/SPI Flash. <bootloader> options: radxa, radxa-debug, edk2-rock5a, edk2-rock5b, armbian."
            #echo "  backup <save_path> : Backup a flashable image of this system."
            #echo "  restore <img_path> : Restore this system from a flashable image. <img_path> : path to the image to restore."
            #echo "  clone <disk> : Clone this system to another disk. <disk> : disk location, example /dev/nvme0n1."
            echo "  sysinfo : Print infomation of this system / device."
            echo "  alias add / create : add an alias / shortcut of a command."
            echo "  alias remove / del : remove an alias created by acu."
            echo
            colorecho "$BLUE" "Manage Packages"
            echo
            echo "  -S / install : show interactive menu to install a collection of apps / packages."
            echo "  -S / install <package> : install a package using acu, you can install multiple packages with one command, example: acu install package1 package4 package3"
            echo "  update : Fetch pacman and acu repositories."
            echo "  upgrade : Check & Perform Selective / Full System Upgrade."
            echo "  -D / downgrade <package> <index> : Install / Downgrade any Arch Linux Packages from Archive. <package>: package name <index>: index to show, default=15."
            echo "  -R / remove : remove / uninstall a package from this system."
            echo "  -B / build <URL> : build / compile a package without installing. <URL> supported protocols: gh://username/repo (GitHub) OR aur://package (AUR) OR https://git_url_to_clone (or http:// or ssh://)"
            echo "  rem / rem fetch : fetch acu managed repositories."
            echo "  rem list / rem show : list acu managed repositories."
            echo "  rem add / rem set <name> <url> : add a repository to acu (pacman and default are reserved name, do not use)."
            echo "  rem add / rem set pacman <name> <url> <gpg_key> : add a repository to acu."
            echo "  rem add / rem set default : load acu default repositories."
            echo "  rem remove / rem del <name> : remove a repository from acu."
            echo "  rem remove / rem del pacman <name>: remove a repository from pacman."
            echo
            colorecho "$BLUE" "Performance"
            echo
            echo "  soc <option> : Manage SoC Settings. options: performance, ondemand, powersave (and status for SoC Monitor) and force-performance which set performance at every bootup."
            echo "  fan <option> : Configure PWM Fan-control. options: install, enable, disable and status."
            echo
            colorecho "$BLUE" "Localization"
            echo
            echo "  locale : Generate Locale Settings. options: list-generated, list-available, generate <country_code>"
            echo "  font : Install Fonts, TTF, Non-English Characters, Special Characters / Emoji."
            echo "  time <option> : Change Time Zone, Current Date and Time. options: set-time-zone, set-time-date, network-time-zone, system-time-zone"
            echo "  keyboard : Change Keyboard Layout."
            echo "  wifi : Change WiFi Country Settings."
            echo
            colorecho "$BLUE" "User Accounts"
            echo
            echo "  user <option> : Add, Remove and Change User Account Settings. options: add, remove, manage"
            exit 0
            ;;
        --loadconfig=*)
            config_file="${arg#*=}"
        ;;  
        -u | --update)
            argupdate=1
        ;;
        --update=*)
            remote_release="${arg#*=}"
            argupdate=1
        ;;
        -y | --yes)
            args=("$@")
            for ((i = 0; i < ${#args[@]}; i++)); do
                if [[ "${args[i]}" == "-y" || "${args[i]}" == "--yes" ]]; then
                    unset 'args[i]'  # Remove -y or --yes from the arguments
                fi
            done
            yes y | acu "${args[@]}"
            exit 0
        ;;
        --noconfirm)
            no_confirm=1
        ;;
        --nowarning)
            no_warning=1
        ;;
        --noclear)
            no_clear=1
        ;;      
        --device=*)
            device_config="${arg#*=}"
            colorecho "$DEBUG" "use target device : $device_config"
        ;;
        --branch=*)
            git_branch="${arg#*=}"
            colorecho "$DEBUG" "clone from branch : $git_branch"
        ;;
        --usepm=*)
            use_pm="${arg#*=}"
        ;;
        -*)
            case "$arg" in
                -S | -R | -D | -B ) 
                    # Add more excluded arguments as needed (these args are handled as features below)
                    ;;
                *)
                    colorecho "$RED" "Invalid command or argument."
                    exit 1
                    ;;
            esac
            ;;
    esac
done

# Initialization
colorecho "$YELLOW" "warning: acu is experimental."

# non-aarch64 system warning
if [ "$system_arch" != "aarch64" ] && [ "$system_arch" != "arm64" ] && [ "$system_arch" != "armv8" ]; then
    colorecho "$YELLOW" "System is $system_arch, Some features are not supported, build command will automatically enable cross-compile (target to aarch64)."
    sleep 1
fi

# Load configurations
load_config

# Debug logging
colorecho "$DEBUG" "Debug logging is enabled"
colorecho "$DEBUG" "Configuration ($config_file):"
colorecho "$DEBUG" ""

# Print loaded ACU Config if debug enabled
if [ -n "$debug_log" ]; then
    print_config_values
fi

# Install / Reinstall / Updates / Auto Update
if [ -n "$argupdate" ] || [ -n "$auto_update" ]; then
    check_util_updates
    update_util "$@"
fi

# make sure it is in a working directory
cd $HOME

### Features - Manage Packages ###
if [ "$1" = "upgrade" ]; then
    package_update

elif [ "$1" = "update" ]; then
    # Fetch pacman repositories updates
    sudo pacman -Syy --noconfirm
    # Update ACU repositories list
    if [ -n "$repositories_file" ] && [ -n "$repositories_url" ]; then
        echo ":: Updating ACU repositories list ..."
        response_code=$(curl --write-out '%{response_code}' -L "$repositories_url" -o tmpdownload.yaml)
        colorecho "$DEBUG" "CURL Response code: $response_code"
        if [ "$response_code" = 200 ]; then
            cp -r tmpdownload.yaml $repositories_file
        else
            colorecho "$RED" "Error: failed to update repositories list."
        fi
        rm -rf tmpdownload.yaml
    fi
    # Update ACU tags list
    if [ -n "$tags_file" ] && [ -n "$tags_url" ]; then
        echo ":: Updating ACU tags list ..."
        response_code=$(curl --write-out '%{response_code}' -L "$tags_url" -o tmpdownload.yaml)
        colorecho "$DEBUG" "CURL Response code: $response_code"
        if [ "$response_code" = 200 ]; then
            cp -r tmpdownload.yaml $tags_file
        else
            colorecho "$RED" "Error: failed to update tags list."
        fi
        rm -rf tmpdownload.yaml
    fi
    # Update ACU kernel list
    if [ -n "$kernel_file" ] && [ -n "$kernel_url" ]; then
        echo ":: Updating ACU kernel list ..."
        response_code=$(curl --write-out '%{response_code}' -L "$kernel_url" -o tmpdownload.yaml)
        colorecho "$DEBUG" "CURL Response code: $response_code"
        if [ "$response_code" = 200 ]; then
            cp -r tmpdownload.yaml $kernel_file
        else
            colorecho "$RED" "Error: failed to update kernel list."
        fi
        rm -rf tmpdownload.yaml
    fi
    # Update ACU bootloader list
    #if [ -n "$bootloader_file" ] && [ -n "$bootloader_url" ]; then
    #    echo ":: Updating ACU bootloader list ..."
    #    response_code=$(curl --write-out '%{response_code}' -L "$bootloader_url" -o tmpdownload.yaml)
    #    colorecho "$DEBUG" "CURL Response code: $response_code"
    #    if [ "$response_code" = 200 ]; then
    #        cp -r tmpdownload.yaml $bootloader_file
    #    else
    #        colorecho "$RED" "Error: failed to update bootloader list."
    #    fi
    #    rm -rf tmpdownload.yaml
    #fi
    # Update ACU apps list
    if [ -n "$apps_file" ] && [ -n "$apps_url" ]; then
        echo ":: Updating ACU apps list ..."
        response_code=$(curl --write-out '%{response_code}' -L "$apps_url" -o tmpdownload.yaml)
        colorecho "$DEBUG" "CURL Response code: $response_code"
        if [ "$response_code" = 200 ]; then
            cp -r tmpdownload.yaml $apps_file
        else
            colorecho "$RED" "Error: failed to update apps list."
        fi
        rm -rf tmpdownload.yaml
    fi    
    # Fetch ACU repositories packages
    fetch_repositories

elif [ "$1" = "remove" ] || [ "$1" = "-R" ]; then
    for ((i = 2; i <= $#; i++)); do
        if [[ "${!i}" != -* ]] && [[ "${!i}" != "acu" ]] && [[ "${!i}" != "agr" ]]; then
            pkgtoremove+=("${!i}")
        elif [[ "${!i}" == "acu" ]]; then
            colorecho "$RED" "Are you sure to remove this utility (acu)? (you wont be able to use acu again if you confirm to remove) [y/N]:" 
            read -r rmconfirm
            case "$rmconfirm" in
                [yY])
                    echo "Removing acu ..."
                    sudo rm -rf /usr/bin/acu
                    sudo rm -rf $HOME/.acu
                    exit 0
                    ;;
                *)
                    echo "acu will NOT be removed."
                    ;;
            esac
        elif [[ "${!i}" == "agr" ]]; then
            if acu rem list | grep -q "Type: agr"; then
                colorecho "$RED" "Are you sure to remove agr? (you wont be able to use acu again if you confirm to remove) [y/N]:" 
                read -r rmagrconfirm
                if [ "$rmagrconfirm" != "y" ] && [ "$rmagrconfirm" != "Y" ]; then
                    exit 1
                fi
                sudo rm -rf ~/.local/bin/agr
                sudo rm -rf ~/.agr
                echo "removed agr"
            fi
        fi
    done
 
    if [ -z "$no_confirm" ]; then
        sudo pacman -R "${pkgtoremove[@]}"
    else
        sudo pacman -R "${pkgtoremove[@]}" --noconfirm
    fi

elif [ "$1" = "install" ] || [ "$1" = "-S" ] ; then
    if [ -z "$2" ]; then
        install_packages
    elif [ "$2" = "--installer" ]; then
        launch_as_installer=1
        install_packages
    else
        for ((i = 2; i <= $#; i++)); do
            if [[ "${!i}" != -* ]]; then
                selection+=("${!i}")
            fi
        done
        install_selected_pkg
    fi

elif [ "$1" = "build" ] || [ "$1" = "-B" ]; then
    if [ -z "$3" ]; then
        install_from_source "$2" "--noinstall"
    else
        install_from_source "$2" "$3" "--noinstall"
    fi
    mkdir -p $HOME/packages/$2
    cp -r "$source_repo_dir"/*.pkg.tar.* $HOME/packages/$2/*.pkg.tar.*
    echo "packages built at $HOME/packages/$2"
    echo "sources located at $HOME/.acu/sources"

elif [ "$1" = "downgrade" ] || [ "$1" = "-D" ]; then
    downgrade_packages "$2" "$3"

elif [ "$1" = "rem" ] || [ "$1" = "remote" ]; then
    if [ -z "$2" ] || [ "$2" = "fetch" ]; then
        fetch_repositories
    elif [ "$2" = "list" ] || [ "$2" = "show" ]; then
        list_repositories
    elif [ "$2" = "set" ] || [ "$2" = "add" ]; then
        if [ "$3" = "pacman" ]; then
            add_repo "$3" "$4" "$5"
        elif [ "$3" = "default" ]; then
            if [ -f "$repositories_file" ]; then
                colorecho "$RED" "Load default repositories file? (This will replace your existing repositories configuration) [y/N]:" 
                read -r rmrepoconfirm
                if [ "$rmrepoconfirm" == "y" ] || [ "$rmrepoconfirm" == "Y" ]; then
                    sudo rm -rf $HOME/.acu/config/repo.yaml
                    acu rem set acu
                    acu rem set adrepo https://api.github.com/repos/kwankiu/archlinux-installer-rock5/releases/tags/kernel
                    acu rem set aur https://aur.archlinux.org
                else
                    echo "No action will be performed."
                fi
            fi

        else
            add_repository "$3" "$4"
        fi
    elif [ "$2" = "del" ] || [ "$2" = "remove" ]; then
        if [ "$3" = "pacman" ]; then
            colorecho "$GREEN" "Auto removing a pacman repo is not yet supported. But you can edit pacman.conf manually, hold on, I will bring you there."
            colorecho "$GREEN" "When you finish, press Ctrl+O to save then press Ctrl+X to exit the editor."
            sleep 2
            sudo nano /etc/pacman.conf
        else
            remove_repository "$3" "$4"
        fi
    fi

### Features - System Maintenance ###
elif [ "$1" = "bootloader" ]; then
    flash_uboot "$2"

### Features - Performance & Features ###
elif [ "$1" = "soc" ]; then
    soc_profile "$2"

elif [ "$1" = "fan" ]; then
    fan_control "$2"

elif [ "$1" = "sysinfo" ]; then
    system_info

### Features - User & Localization ###

elif [ "$1" = "user" ]; then
    manage_user "$2" "$3" "$4"

elif [ "$1" = "locale" ]; then
    locale "$2" "$3" "$4"

elif [ "$1" = "font" ]; then
    fonts "$2"

elif [ "$1" = "time" ]; then
    timezone "$2" "$3"

elif [ "$1" = "keyboard" ]; then
    keyboard "$2"

elif [ "$1" = "wifi" ]; then
    wifi_country "$2"

elif [ "$1" = "alias" ]; then
    if [ "$2" = "add" ] || [ "$2" = "create" ]; then
        add_alias "${@:3}"
    elif [ "$2" = "remove" ] || [ "$2" = "del" ]; then
        sudo rm -rf /usr/bin/$3
        colorecho "$GREEN" "Alias command $3 has been removed."
    fi
### Main Menu ###
elif [ "$1" != "-v" ] && [ "$1" != "--version" ]; then
    check_util_updates
    config_options
fi

################################################################
