# Format of this file is documented at https://github.com/7Ji/arch_repo_builder#config
dephash_strategy: strict
basepkgs: [base-devel, distcc, ccache]
home_binds: [.cache/ccache, .config/ccache]
pkgbuilds:
#  mesa-panfork-git: GH/7Ji-PKGBUILDs/
#  mesa-panfrost-git:
#    url: https://github.com/hbiyik/agrrepo.git
#    subtree: mesa-panfrost-git
#    makedeps:
#      - valgrind
  gitweb-dlagent: GH/7Ji-PKGBUILDs/
  linux-aarch64-rockchip-bsp6.1-joshua-panthor-git:
    url: https://github.com/hbiyik/agrrepo.git
    subtree: kernel/rockchip/linux-aarch64-rockchip-bsp6.1-joshua-panthor-git